// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductModule.Data;

namespace ProductModule.Migrations
{
    [DbContext(typeof(ProductModuleContext))]
    partial class ProductModuleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductModule.Model.Product", b =>
                {
                    b.Property<int>("Prod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Prod_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prod_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prod_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Prod_Qty")
                        .HasColumnType("int");

                    b.Property<string>("Prod_Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Prod_Id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
